package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxAppConfig<M extends BaseWxAppConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAppid(java.lang.String appid) {
		set("appid", appid);
	}

	public java.lang.String getAppid() {
		return get("appid");
	}

	public void setAppsecret(java.lang.String appsecret) {
		set("appsecret", appsecret);
	}

	public java.lang.String getAppsecret() {
		return get("appsecret");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setAccessToken(java.lang.String accessToken) {
		set("access_token", accessToken);
	}

	public java.lang.String getAccessToken() {
		return get("access_token");
	}

	public void setAccessTokenExpires(java.util.Date accessTokenExpires) {
		set("access_token_expires", accessTokenExpires);
	}

	public java.util.Date getAccessTokenExpires() {
		return get("access_token_expires");
	}

	public void setApiTicket(java.lang.String apiTicket) {
		set("api_ticket", apiTicket);
	}

	public java.lang.String getApiTicket() {
		return get("api_ticket");
	}

	public void setApiTicketExpires(java.util.Date apiTicketExpires) {
		set("api_ticket_expires", apiTicketExpires);
	}

	public java.util.Date getApiTicketExpires() {
		return get("api_ticket_expires");
	}

}
