package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewbee<M extends BaseNewbee<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("gameId", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("gameId");
	}

	public void setGameName(java.lang.String gameName) {
		set("gameName", gameName);
	}

	public java.lang.String getGameName() {
		return get("gameName");
	}

	public void setPathName(java.lang.String pathName) {
		set("pathName", pathName);
	}

	public java.lang.String getPathName() {
		return get("pathName");
	}

	public void setMean(java.math.BigDecimal mean) {
		set("mean", mean);
	}

	public java.math.BigDecimal getMean() {
		return get("mean");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setStd(java.math.BigDecimal std) {
		set("std", std);
	}

	public java.math.BigDecimal getStd() {
		return get("std");
	}

}
