package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrainClass<M extends BaseTrainClass<M>> extends Model<M> implements IBean {

	public void setTrainClassId(java.lang.Integer trainClassId) {
		set("trainClassId", trainClassId);
	}

	public java.lang.Integer getTrainClassId() {
		return get("trainClassId");
	}

	public void setTrainClassName(java.lang.String trainClassName) {
		set("trainClassName", trainClassName);
	}

	public java.lang.String getTrainClassName() {
		return get("trainClassName");
	}

	public void setTrainFileName(java.lang.String trainFileName) {
		set("trainFileName", trainFileName);
	}

	public java.lang.String getTrainFileName() {
		return get("trainFileName");
	}

	public void setTraindis(java.lang.String traindis) {
		set("traindis", traindis);
	}

	public java.lang.String getTraindis() {
		return get("traindis");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreateAdminId(java.lang.Integer createAdminId) {
		set("createAdminId", createAdminId);
	}

	public java.lang.Integer getCreateAdminId() {
		return get("createAdminId");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setUpdateAdminId(java.lang.Integer updateAdminId) {
		set("updateAdminId", updateAdminId);
	}

	public java.lang.Integer getUpdateAdminId() {
		return get("updateAdminId");
	}

	public void setIsList(java.lang.Integer isList) {
		set("is_list", isList);
	}

	public java.lang.Integer getIsList() {
		return get("is_list");
	}

}
