package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrialRecord<M extends BaseTrialRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTaAdminId(java.lang.Long taAdminId) {
		set("ta_admin_id", taAdminId);
	}

	public java.lang.Long getTaAdminId() {
		return get("ta_admin_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setDuration(java.lang.Integer duration) {
		set("duration", duration);
	}

	public java.lang.Integer getDuration() {
		return get("duration");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

}
