package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrialAdmin<M extends BaseTrialAdmin<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setWxOpenid(java.lang.String wxOpenid) {
		set("wx_openid", wxOpenid);
	}

	public java.lang.String getWxOpenid() {
		return get("wx_openid");
	}

	public void setWxNickname(java.lang.String wxNickname) {
		set("wx_nickname", wxNickname);
	}

	public java.lang.String getWxNickname() {
		return get("wx_nickname");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setAllocateNum(java.lang.Integer allocateNum) {
		set("allocate_num", allocateNum);
	}

	public java.lang.Integer getAllocateNum() {
		return get("allocate_num");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setInvalidate(java.lang.Integer invalidate) {
		set("invalidate", invalidate);
	}

	public java.lang.Integer getInvalidate() {
		return get("invalidate");
	}

}
