package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrialAdminTemp<M extends BaseTrialAdminTemp<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setVouch(java.lang.String vouch) {
		set("vouch", vouch);
	}

	public java.lang.String getVouch() {
		return get("vouch");
	}

	public void setWxOpenid(java.lang.String wxOpenid) {
		set("wx_openid", wxOpenid);
	}

	public java.lang.String getWxOpenid() {
		return get("wx_openid");
	}

	public void setExpires(java.util.Date expires) {
		set("expires", expires);
	}

	public java.util.Date getExpires() {
		return get("expires");
	}

	public void setWxNickname(java.lang.String wxNickname) {
		set("wx_nickname", wxNickname);
	}

	public java.lang.String getWxNickname() {
		return get("wx_nickname");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
