package com.lumosity.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("about", "aboutId", About.class);
		arp.addMapping("account", "userId", Account.class);
		arp.addMapping("brain_class_profile", "profileId", BrainClassProfile.class);
		arp.addMapping("brain_profile", "userId", BrainProfile.class);
		arp.addMapping("comment", "commentId", Comment.class);
		arp.addMapping("day_class_record", "recordId", DayClassRecord.class);
		arp.addMapping("day_game_record", "recordId", DayGameRecord.class);
		arp.addMapping("day_record", "recordId", DayRecord.class);
		arp.addMapping("education", "eduDegreeId", Education.class);
		arp.addMapping("game", "gameId", Game.class);
		arp.addMapping("game_class", "gameClassId", GameClass.class);
		arp.addMapping("game_class_price", "id", GameClassPrice.class);
		arp.addMapping("game_class_time", "id", GameClassTime.class);
		arp.addMapping("game_history", "gameHistoryId", GameHistory.class);
		arp.addMapping("ios_receipt", "id", IosReceipt.class);
		arp.addMapping("job", "jobId", Job.class);
		arp.addMapping("newbee", "id", Newbee.class);
		arp.addMapping("order", "orderId", Order.class);
		arp.addMapping("plan_game", "planGameId", PlanGame.class);
		arp.addMapping("price_base", "priceBaseId", PriceBase.class);
		arp.addMapping("price_personal", "id", PricePersonal.class);
		arp.addMapping("question_status", "userId", QuestionStatus.class);
		arp.addMapping("session", "sessionId", Session.class);
		arp.addMapping("tb_oauth", "id", OauthUser.class);
		arp.addMapping("test_plan", "testId", TestPlan.class);
		arp.addMapping("time_length", "id", TimeLength.class);
		arp.addMapping("train_class", "trainClassId", TrainClass.class);
		arp.addMapping("train_plan", "trainPlanId", TrainPlan.class);
		arp.addMapping("train_prefer", "userId", TrainPrefer.class);
		arp.addMapping("trial_admin", "id", TrialAdmin.class);
		arp.addMapping("trial_admin_temp", "id", TrialAdminTemp.class);
		arp.addMapping("trial_record", "id", TrialRecord.class);
		arp.addMapping("user_game", "userGameId", UserGame.class);
		arp.addMapping("wang", "id", Wang.class);
		arp.addMapping("week_class_record", "recordId", WeekClassRecord.class);
		arp.addMapping("week_record", "recordId", WeekRecord.class);
		arp.addMapping("wx_app_config", "id", WxAppConfig.class);
	}
}

