package com.lumosity.model;

import com.lumosity.model.base.BaseGameClassPrice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameClassPrice extends BaseGameClassPrice<GameClassPrice> {
	public static final GameClassPrice dao = new GameClassPrice();
}
