package com.lumosity.model;

import com.lumosity.model.base.BaseGameClassTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameClassTime extends BaseGameClassTime<GameClassTime> {
	public static final GameClassTime dao = new GameClassTime();
}
