package com.lumosity.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.lumosity.model.base.BasePriceBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PriceBase extends BasePriceBase<PriceBase> {
	public static final PriceBase dao = new PriceBase();
	
	/**
	 * 根据大类查询定价方案
	 * @param trainClassId
	 * @return
	 */
	public List<Record> findByTrainClassId(Integer trainClassId) {
		String sql = " SELECT pb.priceBaseId,pb.`baseDetail`,pb.`gameDate`,pb.`outPrice`,dd.`name` FROM `price_base` pb " +
					 " LEFT JOIN dict_data dd ON pb.`gameDate` = dd.`id` " +
					 " WHERE pb.`trainClassId` = ? AND pb.`priceBaseType` = 1";
		return Db.find(sql, trainClassId);
	}
}
