package com.lumosity.model;

import com.lumosity.model.base.BasePricePersonal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PricePersonal extends BasePricePersonal<PricePersonal> {
	public static final PricePersonal dao = new PricePersonal();
}
