package com.lumosity.model;

import org.apache.commons.lang3.StringUtils;

import com.lumosity.model.base.BaseQuestionStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionStatus extends BaseQuestionStatus<QuestionStatus> {
	public static final QuestionStatus dao = new QuestionStatus();

	public float[] findAbilityCount(Long userId) {
		String sql = "select * from question_status qs where qs.userId = ?";
		QuestionStatus qs = findFirst(sql, userId);
		String survey = qs.getSurvey();
		float[] result = new float[] { 0, 0, 0, 0, 0 };
		if (StringUtils.isBlank(survey))
			return result;
		String[] suerveys = survey.split(";");
		if (suerveys.length < 5)
			return result;
		for (int i = 0; i < 5; i++) {
			String question = suerveys[i];
			String[] qs2 = question.split(":");
			String value = qs2[1];
			int abilityCount = value.split(",").length;
			result[i] = abilityCount;
		}
		return result;
	}
	
	public boolean findStatus(Long userId) {
		QuestionStatus questionStatus = findFirst("select * from question_status qs where qs.userId = ?", userId);
		if (questionStatus.getQuestion1Status() == 1 && questionStatus.getQuestion2Status() == 1) {
			return true;
		}
		return false;
	}
	
}
