package com.lumosity.model;

import com.lumosity.model.base.BaseTbOauth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbOauth extends BaseTbOauth<TbOauth> {
	public static final TbOauth dao = new TbOauth();
}
