package com.lumosity.model;

import java.util.List;

import com.lumosity.model.base.BaseTestPlan;
import com.lumosity.utils.DateTimeKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestPlan extends BaseTestPlan<TestPlan> {
	public static final TestPlan dao = new TestPlan();
	
	public List<TestPlan> findByUser(Long id) {
		return find("select * from test_plan where userId =? order by sequence", id);
		
	}
	public List<TestPlan> remaining(Long id) {
		return find("select testId,userId,gameId,sequence,isPlay from test_plan where userId =? and isPlay=0 order by sequence", id);
		
	}
	public TestPlan findByUserAndSquence(Long id, int sqe) {
		return findFirst("select * from test_plan where userId =? and sequence =?", id, sqe);
	}
	
	public TestPlan findLastSquenceByUserId(Long id) {
		return findFirst("SELECT * FROM test_plan tp WHERE tp.`userId` = ? AND tp.`isPlay` = 0 ORDER BY tp.`sequence`", id);
	}
	
	/**
	 * 保存适应性训练数据
	 * (与正式训练数据分开)
	 * @param score
	 * @param gameLPI
	 * @param gameDate
	 */
	public void saveGameDate(Integer score, Integer gameLPI, String gameData) {
		 set("isPlay", 1)
		.set("score", score)
		.set("gameLPI", gameLPI)
		.set("gameData", gameData)
		.set("playDate", DateTimeKit.getDate())
		.update();
	}
}
