package com.lumosity.model;

import com.lumosity.model.base.BaseTimeLength;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TimeLength extends BaseTimeLength<TimeLength> {
	public static final TimeLength dao = new TimeLength();
}
