package com.lumosity.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.lumosity.model.base.BaseTrainClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrainClass extends BaseTrainClass<TrainClass> {
	public static final TrainClass dao = new TrainClass();
	
	/**查询所有记录**/
	public List<TrainClass> findAll() {
		return find("select * from train_class");
	}
	
	/**
	 * 查询已上架大类列表
	 * @return
	 */
	public List<Record> findNormalList() {
		return Db.find("select * from train_class tc where tc.is_list = 1");
	}
}
