package com.lumosity.model;

import com.lumosity.model.base.BaseTrialAdminTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrialAdminTemp extends BaseTrialAdminTemp<TrialAdminTemp> {
	public static final TrialAdminTemp dao = new TrialAdminTemp();
}
