package com.lumosity.model;

import com.lumosity.model.base.BaseTrialRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrialRecord extends BaseTrialRecord<TrialRecord> {
	public static final TrialRecord dao = new TrialRecord();
}
