package com.lumosity.model;

import com.lumosity.model.base.BaseTrialAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrialAdmin extends BaseTrialAdmin<TrialAdmin> {
	public static final TrialAdmin dao = new TrialAdmin();
}
