package com.lumosity.model;

import com.lumosity.model.base.BaseWang;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Wang extends BaseWang<Wang> {
	public static final Wang dao = new Wang();
}
